# main.py
from automovil import Automovil
from barco import Barco
from avion import Avion
from sedan import Sedan

def main():
    # Crear un Automóvil
    automovil = Automovil()
    automovil.set_marca("Toyota")
    automovil.set_anio("2023")
    automovil.set_color("Negro Matte")
    automovil.set_peso(1360)
    automovil.set_longitud(4.37)
    automovil.set_altura(1455)
    automovil.set_ancho(1780)
    automovil.set_garantia("3 años")
    automovil.set_material_carroceria("Lamina")
    automovil.set_capacidad_pasajeros("5 personas")
    automovil.set_capacidad_carga(425)
    automovil.set_numero_cilindros(4)
    automovil.set_potencia_motor("150 HP")
    automovil.set_aceleracion_0_100("100 km/h")
    automovil.set_tipo_combustible("Gasolina")
    automovil.set_grado_anticongelante("00272-1LLAC")
    automovil.set_numero_serie_motor("JKFWL67T3Y4JRBM")
    automovil.set_frecuencia_aceite("50%")
    automovil.set_consumo_combustible_motor(9.7)
    automovil.set_numero_puertas(4)
    automovil.set_numero_bolsas_aire(4)
    automovil.set_asistencia_seguro("si")
    automovil.set_tipo_llantas("Verano")
    automovil.set_tamano_llantas("205/55R16")
    automovil.set_presion_llantas(2.2)
    automovil.set_material_llantas("Caucho natural y Sintetico")
    automovil.set_diferencial_llantas("HTY56")
    automovil.set_material_rines("Aleacion de aluminio")

    print("Información del Automóvil:")
    for info in automovil.mostrar_Informacion_Automovil():
        print(info)
    print("-" * 40)

    # Crear un Barco
    barco = Barco()
    barco.set_marca("Royal Caribbean International")
    barco.set_anio("2022")
    barco.set_color("Blanco Hueso")
    barco.set_peso(16500000)
    barco.set_longitud(10.20)
    barco.set_altura(3.30)
    barco.set_ancho(70)
    barco.set_material_carroceria("Aleacion de Cobre y Aluminio")
    barco.set_capacidad_pasajeros("100 personas")
    barco.set_capacidad_carga(50000)
    barco.set_numero_cilindros(14)
    barco.set_potencia_motor("5000 HP")
    barco.set_aceleracion_0_100("37 km/h")
    barco.set_tipo_combustible("Disel")
    barco.set_grado_anticongelante("60%")
    barco.set_numero_serie_motor("KJ8O83470")
    barco.set_frecuencia_aceite("Grasa dielectrica")
    barco.set_camarotes(5088)
    barco.set_equipo_salvavidas("si")
    barco.set_capacidad_pasajeros(10)
    barco.set_sistema_navegacion("Plotter")
    barco.set_tipo_poniente("Clasica")
    barco.set_sistema_vapor("No integrado")

    print("Información del Barco:")
    for info in barco.mostrar_Informacion_Barco():
        print(info)
    print("-" * 40)

    # Crear un Avión
    avion = Avion()
    avion.set_marca("Boeing")
    avion.set_anio("2020")
    avion.set_color("Blanco Aperlado")
    avion.set_peso(19500)
    avion.set_longitud(39.47)
    avion.set_altura(12.60)
    avion.set_ancho(30)
    avion.set_material_carroceria("Chapa de Metal")
    avion.set_capacidad_pasajeros("180 personas")
    avion.set_capacidad_carga(6000)
    avion.set_numero_cilindros(6)
    avion.set_potencia_motor("1341 HP")
    avion.set_aceleracion_0_100("240 km/h")
    avion.set_tipo_combustible("Queroseno")
    avion.set_grado_anticongelante("80%")
    avion.set_numero_serie_motor("JWD876R5NHSZ")
    avion.set_frecuencia_aceite("Aeroshell Fluid 12")
    avion.set_envergadura(60.1)
    avion.set_altitud_maxima(9000)
    avion.set_sistema_oxigeno("si")
    avion.set_pista_minima_despegue("2 kilometros")
    avion.set_pista_minima_aterrizaje("200 pies")

    print("Información del Avión:")
    for info in avion.mostrar_Informacion_Avion():
        print(info)
    print("-" * 40)

    # Crear una Camioneta
    sedan = Sedan()
    sedan.set_marca("Ford")
    sedan.set_modelo("F-150")
    sedan.set_anio("2023")
    sedan.set_color("Rojo Carmesi")
    sedan.set_peso(180)
    sedan.set_longitud(.70)
    sedan.set_altura(1.60)
    sedan.set_ancho(80)
    sedan.set_garantia("1 año")
    sedan.set_material_carroceria("Acero y Aluminio")
    sedan.set_capacidad_pasajeros("2 personas")
    sedan.set_capacidad_carga(12)
    sedan.set_numero_cilindros(2)
    sedan.set_potencia_motor("200 HP")
    sedan.set_aceleracion_0_100("100 m/s")
    sedan.set_tipo_combustible("Gasolina")
    sedan.set_grado_anticongelante("40%")
    sedan.set_numero_serie_motor("OIEFU3NJNG834")
    sedan.set_frecuencia_aceite("Gurllet 12")
    sedan.set_tamano_llantas("265/70R17")
    sedan.set_tipo_llantas("Pista")
    sedan.set_presion_llantas(1.5)
    sedan.set_material_llantas("Caucho")
    sedan.set_diferencial_llantas("HT950")
    sedan.set_material_rines("Aluminio")
    sedan.set_sistema_turbo("Secuencial")
    sedan.set_espejos_retrovisores("2")
    sedan.set_techo_solar("Spoiler")

    print("Información de la Sedan:")
    for info in sedan.mostrar_Informacion_Sedan():
        print(info)
    print("-" * 40)


if __name__ == "__main__":
    main()
