# main.py
from automovil import Automovil
from barco import Barco
from avion import Avion
from motocicleta import Motocicleta


def main():
    # Crear un Automóvil
    automovil = Automovil()
    automovil.set_marca("Toyota")
    automovil.set_modelo("Corolla")
    automovil.set_anio("2023")
    automovil.set_color("Negro Matte")
    automovil.set_peso(1360)
    automovil.set_longitud(4.37)
    automovil.set_altura(1455)
    automovil.set_ancho(1780)
    automovil.set_garantia("3 años")
    automovil.set_tipo_carroceria("Carroceria Sedan y Familiar")
    automovil.set_material_carroceria("Acero")
    automovil.set_capacidad_pasajeros("5 personas")
    automovil.set_capacidad_carga(425)
    automovil.set_catidad_llantas(4)
    automovil.set_numero_cilindros(4)
    automovil.set_potencia_motor("139/6100 hp/rpm")
    automovil.set_torque("126/3900")
    automovil.set_aceleracion_0_100("N/D")
    automovil.set_tipo_combustible("Gasolina")
    automovil.set_tipo_transmision_motor("Automatica")
    automovil.set_grado_anticongelante("00272-1LLAC")
    automovil.set_numero_serie_motor("JKFWL67T3Y4JRBM")
    automovil.set_tipo_direccion("Electroasistida")
    automovil.set_sistema_suspension("McPherson (Independiente)")
    automovil.set_frecuencia_aceite("50%")
    automovil.set_consumo_combustible_motor(9.7)
    automovil.set_numero_puertas(4)
    automovil.set_tipo_vehiculo("Sedán")
    automovil.set_techo_solar("si")
    automovil.set_numero_bolsas_aire(4)
    automovil.set_sistema_alarma("si")
    automovil.set_sistema_frenos("Disco")
    automovil.set_asistencia_seguro("si")
    automovil.set_sensores_lluvia("si")
    automovil.set_tipo_llantas("Verano")
    automovil.set_tamano_llantas("205/55R16")
    automovil.set_presion_llantas(2.2)
    automovil.set_material_llantas("Caucho natural y Sintetico")
    automovil.set_diferencial_llantas("HTY56")
    automovil.set_velocidad_maxima_llantas("142 mph")
    automovil.set_durabilidad_llantas(10000)
    automovil.set_alineacion(2700)
    automovil.set_rueda_reserva("si")
    automovil.set_material_rines("Aleacion de aluminio")
    automovil.set_peso_llanta(6)


    print("Información del Automóvil:")
    for info in automovil.mostrar_Informacion_Automovil():
        print(info)
    print("-" * 40)

    # Crear un Barco
    barco = Barco()
    barco.set_marca("Yamaha")
    barco.set_modelo("242X")
    barco.set_anio("2022")
    barco.set_color("Blanco Hueso")
    barco.set_peso(16500000)
    barco.set_longitud(10.20)
    barco.set_altura(3.30)
    barco.set_ancho(70)
    barco.set_garantia("5 años")
    barco.set_tipo_carroceria("COUPE")
    barco.set_material_carroceria("Aleacion de Cobre y Aluminio")
    barco.set_capacidad_pasajeros("100 personas")
    barco.set_capacidad_carga(50000)
    barco.set_catidad_llantas(0)
    barco.set_numero_cilindros(7)
    barco.set_potencia_motor("17 Caballos de Fuerza")
    barco.set_torque("354/3087")
    barco.set_aceleracion_0_100("350 HP")
    barco.set_tipo_combustible("Disel")
    barco.set_tipo_transmision_motor("Ejes")
    barco.set_grado_anticongelante("60%")
    barco.set_numero_serie_motor("KJ8O83470")
    barco.set_tipo_direccion("Mecanicos")
    barco.set_frecuencia_aceite("Grasa dielectrica")
    barco.set_tipo_barco("Yate")
    barco.set_cabinas(2)
    barco.set_tipo_uso("Personal")
    barco.set_equipo_salvavidas("si")
    barco.set_capacidad_pasajeros(10)
    barco.set_popa("Eliptica")
    barco.set_proa("Straing Stern")
    barco.set_sistema_navegacion("Plotter")
    barco.set_tipo_poniente("Clasica")
    barco.set_sistema_desagote("Sistema de Achique")
    barco.set_sistema_vapor("No integrado")

    print("Información del Barco:")
    for info in barco.mostrar_Informacion_Barco():
        print(info)
    print("-" * 40)

    # Crear un Avión
    avion = Avion()
    avion.set_marca("Boeing")
    avion.set_modelo("737")
    avion.set_anio("2020")
    avion.set_color("Blanco Aperlado")
    avion.set_peso(19500)
    avion.set_longitud(39.47)
    avion.set_altura(12.60)
    avion.set_ancho(30)
    avion.set_garantia("25 años")
    avion.set_tipo_carroceria("Jet Fuel")
    avion.set_material_carroceria("Chapa de Metal")
    avion.set_capacidad_pasajeros("180 personas")
    avion.set_capacidad_carga(6000)
    avion.set_catidad_llantas(3)
    avion.set_numero_cilindros(6)
    avion.set_potencia_motor("175000 Caballos de potencia")
    avion.set_torque("18454/3090")
    avion.set_aceleracion_0_100("10000 HP")
    avion.set_tipo_combustible("Queroseno")
    avion.set_tipo_transmision_motor("Electromagnetica")
    avion.set_grado_anticongelante("80%")
    avion.set_numero_serie_motor("JWD876R5NHSZ")
    avion.set_tipo_direccion("Radinavegacion")
    avion.set_sistema_suspension("Tren aterrizaje")
    avion.set_frecuencia_aceite("Aeroshell Fluid 12")
    avion.set_tipo_avion("Comercial")
    avion.set_peso_maximo_despegue(180)
    avion.set_envergadura(60.1)
    avion.set_altitud_maxima(9000)
    avion.set_sistema_oxigeno("si")
    avion.set_sistemas_safety("ZoneSafe")
    avion.set_sistemas_autopiloto("Sistema de navegacion inercial (INS)")
    avion.set_pista_minima_despegue("2 kilometros")
    avion.set_pista_minima_aterrizaje("200 pies")
    avion.set_tipo_vuelo("Internacionales")
    avion.set_antena_comunicaciones("VHF")
    avion.set_clase_servicios("Primera clase")

    print("Información del Avión:")
    for info in avion.mostrar_Informacion_Avion():
        print(info)
    print("-" * 40)

    # Crear una Camioneta
    motocicleta = Motocicleta()
    motocicleta.set_marca("Ford")
    motocicleta.set_modelo("F-150")
    motocicleta.set_anio("2023")
    motocicleta.set_color("Rojo Carmesi")
    motocicleta.set_peso(180)
    motocicleta.set_longitud(.70)
    motocicleta.set_altura(1.60)
    motocicleta.set_ancho(80)
    motocicleta.set_garantia("1 año")
    motocicleta.set_tipo_carroceria("Deportivo")
    motocicleta.set_material_carroceria("Acero y Aluminio")
    motocicleta.set_capacidad_pasajeros("2 personas")
    motocicleta.set_capacidad_carga(12)
    motocicleta.set_catidad_llantas(2)
    motocicleta.set_numero_cilindros(2)
    motocicleta.set_potencia_motor("7000 RPM")
    motocicleta.set_torque("70/600")
    motocicleta.set_aceleracion_0_100("16 HP")
    motocicleta.set_tipo_combustible("Gasolina")
    motocicleta.set_tipo_transmision_motor("Por cadena")
    motocicleta.set_grado_anticongelante("40%")
    motocicleta.set_numero_serie_motor("OIEFU3NJNG834")
    motocicleta.set_tipo_direccion("Paralelogramo")
    motocicleta.set_sistema_suspension("Amortiguadores")
    motocicleta.set_frecuencia_aceite("Gurllet 12")
    motocicleta.set_tipo_vehiculo("Pick-up")
    motocicleta.set_tipo_llantas("Todo terreno")
    motocicleta.set_tamano_llantas("265/70R17")
    motocicleta.set_tipo_llantas("Pista")
    motocicleta.set_presion_llantas(1.5)
    motocicleta.set_material_llantas("Caucho")
    motocicleta.set_diferencial_llantas("HT950")
    motocicleta.set_velocidad_maxima_llantas("243 mph")
    motocicleta.set_durabilidad_llantas(18000)
    motocicleta.set_alineacion(250)
    motocicleta.set_rueda_reserva("No")
    motocicleta.set_material_rines("Aluminio")
    motocicleta.set_peso_llanta(3)
    motocicleta.set_tamano_respaldo(30)
    motocicleta.set_indicadores_fluorescentes(False)
    motocicleta.set_capacidad_baul(40)
    motocicleta.set_tipo_guardabarros("Trasero")
    motocicleta.set_anclaje_asiento_pasajero("Cojin de Gel")
    motocicleta.set_tipo_estriberas("Plasticas")
    motocicleta.set_proteccion_codo("Algodon")
    motocicleta.set_sistema_deteccion_caida(True)
    motocicleta.set_soporte_manos(True)
    motocicleta.set_sistema_turbo("Secuencial")
    motocicleta.set_espejos_retrovisores(True)

    print("Información de la Camioneta:")
    for info in motocicleta.mostrar_Informacion_Motocicleta():
        print(info)
    print("-" * 40)


if __name__ == "__main__":
    main()
